server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  data:
    mongodb:
      database: dbBankCredit
      port: 27017
      host: localhost
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: 'true'
info:
  app:
    name: Spring Boot Actuator Api Bank Credit
    web: '*'
  hello: Hi here!
logging:
  level:
    root: info
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

resilience4j.circuitbreaker:
  instances:
    services:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 20
      waitDurationInOpenState: 15s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10