management:
  endpoints:
    web:
      exposure:
        include: *
  endpoint:
    shutdown:
      enabled: true
spring:
  application:
    name: api-transaction
  data:
    mongodb:
      database: dbTransaction
      port: 27017
      host: localhost
server:
  port: 8085