management:
  endpoints:
    web:
      exposure:
        include: *
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
info:
  app:
    name: Spring Boot Actuator Api Bank Credit
    web: *
  hello: Hi here!
spring:
  application:
    name: api-bankcredit
  data:
    mongodb:
      database: dbBankCredit
      port: 27017
      host: localhost
server:
  port: 8083
logging:
  level:
    root: info