management:
  endpoints:
    web:
      exposure:
        include: *
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
info:
  app:
    name: Spring Boot Actuator Api Transaction
  hello: Hi here!
spring:
  application:
    name: api-transaction
  data:
    mongodb:
      database: dbTransaction
      port: 27017
      host: localhost
server:
  port: 8085
logging:
  level:
    root: info
