server:
  port: 8082
spring:
  data:
    mongodb:
      database: dbClientBank
      port: 27017
      host: localhost
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show:
        details: always
  endpoints:
    web:
      exposure:
        include: *