server:
  port: 8001
spring:
  cloud:
    config:
      server:
        git:
          default-label: gateway
          uri: https://github.com/cesarOcampoDiaz/micro-services
          search-paths: config-data
  application:
    name: config-server